### ISSUE TITLE
Support for generating shares without encrypting them

### ISSUE THREAD

**Issue by jvsg** [abetterinternet/libprio-rs#38]
This library might be used in a program that already encrypts/decrypts shares on it's own. In that case, the library should generate shares in plaintext.

Does this seem like an worthwhile idea? I can make a pull request for the work i did.

**Comment by cjpatton** [comment]
I agree that this is something we'll need. What you mind sketching the API you had in mind? A few criteria I would start with:
1. The thing that is secret shared ought to be the concatenation of the input and proof vectors.
2. The caller should provide a PRNG seed used to generate an aggregator's share.
3. It should be possible to split the input/proof into more than two shares.

**Comment by jvsg** [comment]
I had to use prio in a project of my own so hacked on it. My solution makes use of conditional compilation (I love C++), so the caller doesn't have to deal with passing a parameter, but the source code looks a bit ugly because entire functions needed to be duplicated.

Your points 1 and 2 are worthwhile to work upon. I have implemented point 3 to some extent, though need some time to make a pull request for it. And point 3 also requires having support for multiple (>2) servers. Afterall, multiple servers make use of multiple shares.

I'm unfamiliar with `prio::pcp`. Could you point me towards it?

**Comment by cjpatton** [comment]
> I'm unfamiliar with `prio::pcp`. Could you point me towards it?

I'm referring to the module here: https://github.com/abetterinternet/libprio-rs/blob/main/src/pcp.rs
 
> Edit: Do you think it's a fine approach?

IMO, using conditional compilation to configure encryption vs non-encryption isn't the best approach because some applications might want to do both. I think a better approach would be expose an API for secret sharing the input and proof.

**Comment by cjpatton** [comment]
Hi @jvsg, in case you missed it: We recently began implementing a new module, `vdaf`, that constructs secret shares without encrypting them. It's still WIP so please don't depend on it yet. In the meantime, please take a look and see if that will meet your needs.
